{{- if .Values.envSecretProperties }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atomic-request-metadata.fullname" . }}
  labels:
    {{- include "atomic-request-metadata.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.envSecretProperties }}
  {{ $key }}: {{ $value | default "" | b64enc | quote }}
  {{- end }}
{{- end }}
